x = int(input("enter the first no"))
y = int(input("enter the second no"))
print("The value of 3+2 is",x+y)
print("The value of 3\2 is",x/y)
print("The value of 3*2 is",x*y)
print("The value of 3-2 is",x-y)